server:
  address: localhost
  port: 8080

spring:
  profiles:
    active: db
  config:
    import: application-db.yml

  datasource:
    driver-class-name: ${driver-class-name}
    url : ${url}
    username: ${username}
    password: ${password}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql
    show-sql: true
