server:
  address: localhost
  port: 8080

spring:
  profiles:
    active: db
  config:
    import: application-db.yml

  mail:
    host: smtp.gmail.com
    port: 587
    username_: ${username}
    password_: ${password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection timeout: 5000
          timeout: 5000
          write timeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분

  datasource:
    driver-class-name: ${driver-class-name}
    url : ${url}
    username: ${username}
    password: ${password}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql
    show-sql: true

  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
