server:
  address: localhost
  port: 8080

spring:
  profiles:
    active: db
  config:
    import: application-db.yml

  datasource:
    driver-class-name: ${driver-class-name}
    url : ${url}
    username: ${username}
    password: ${password}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql
    show-sql: true

jwt:
  expiration_time: 86400000
  secret: 553e8326984a2698d7b4bcef7741d885e43bd188b47b2d35ad08d98ffb30537b
